<?php defined("APP")?assert(true):die();

// generated by https://cookieconsent.insites.com/download/

?>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cf async="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#eaf7f7",
      "text": "#5c7291"
    },
    "button": {
      "background": "transparent",
      "text": "#56cbdb",
      "border": "#56cbdb"
    }
  },
  "position": "bottom-right",
  "content": {
    "dismiss": "No worries!",
    "href": "https://www.coursesuite.com/privacy"
  }
});
</script>